/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bd.*;
import com.mysql.jdbc.exceptions.MySQLSyntaxErrorException;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import model.*;

/**
 *
 * @author mariano
 */
public class Leitor extends javax.swing.JFrame {
    private Map<String, String> inventarioNomes;
    private Map<String, String> inventarioValores;
    
    /**
     * Creates new form Leitor
     */
    public Leitor() {
        inventarioNomes = new HashMap<>(); 
        inventarioValores = new HashMap<>(); 
        
        //inventario.put(456, new Produtos(123456, "cafeee",     450, "pilao",        50,     "gr") );
        //inventario.put(123,new Produtos(123456, "cafeee",     450, "pilao",        50,     "gr") );               
        initComponents();        
        
        Conexao sql = Conexao.getInstance();
        
        try {     
            // 1-Get a connection  to database
            //Connection con = DriverManager.getConnection("jdbc:mysql://localhost/supermercado", "poo", "poo");
           
            // 2-Create a statement
            Statement myState = sql.getConnection().createStatement();
            // 3-Execute SQL query 
            String query = "SELECT *"
                           + "FROM produtos";
                    
            ResultSet resulado = myState.executeQuery(query);                                
            // 4-Process the result set
            while (resulado.next()){
                inventarioNomes.put(resulado.getString("codigo"),resulado.getString("nome") +" " + 
                                    resulado.getString("marca")+ " " +
                                    resulado.getString("tamanho") + " " +
                                    resulado.getString("unidade")
                        );
                inventarioValores.put(resulado.getString("codigo"),resulado.getString("valor"));	

            }
            
        }catch(SQLException sqle){
            System.out.println(sqle);

        }catch(Exception e){
            System.out.println(" algum outro erro ");
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        tituloLeito = new java.awt.Label();
        inputCodigoTextField = new java.awt.TextField();
        botaoConsultar = new java.awt.Button();
        panel2 = new java.awt.Panel();
        nomeProdutoTextField = new javax.swing.JTextField();
        valorDoProdutoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloLeito.setAlignment(java.awt.Label.CENTER);
        tituloLeito.setText("Inserir o codigo do produto que deseja consultar");

        inputCodigoTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        inputCodigoTextField.setText("escreva aqui o codigo do produto");
        inputCodigoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputCodigoTextFieldMouseClicked(evt);
            }
        });

        botaoConsultar.setBackground(new java.awt.Color(255, 255, 51));
        botaoConsultar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoConsultar.setLabel("CONSULTAR");
        botaoConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoConsultarMousePressed(evt);
            }
        });
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(inputCodigoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLeito, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputCodigoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        nomeProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeProdutoTextField.setToolTipText("");

        valorDoProdutoTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        valorDoProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorDoProdutoTextField)
                    .addComponent(nomeProdutoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorDoProdutoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCodigoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCodigoTextFieldMouseClicked
        inputCodigoTextField.setText("");
    }//GEN-LAST:event_inputCodigoTextFieldMouseClicked

    private void botaoConsultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarMousePressed
      
        try{            
            Double valor = Integer.parseInt(inventarioValores.get(inputCodigoTextField.getText()))/100.0;
            
            nomeProdutoTextField.setText(inventarioNomes.get(inputCodigoTextField.getText()));           
            valorDoProdutoTextField.setText("R$ " + valor.toString());
            
        }
        catch(NullPointerException npe){
            nomeProdutoTextField.setText("- PRODUTO NAO CADASTRADO. NPE-");
        }catch(Exception e){
            nomeProdutoTextField.setText("- PRODUTO NAO CADASTRADO -");
        }        
    }//GEN-LAST:event_botaoConsultarMousePressed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
         
        
    }//GEN-LAST:event_botaoConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    java.awt.Button botaoConsultar;
    java.awt.TextField inputCodigoTextField;
    javax.swing.JTextField nomeProdutoTextField;
    java.awt.Panel panel1;
    java.awt.Panel panel2;
    java.awt.Label tituloLeito;
    javax.swing.JTextField valorDoProdutoTextField;
    // End of variables declaration//GEN-END:variables
}
