/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Cecília
 */
public class TelaCaixa extends javax.swing.JFrame {

    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        labelUltimoItem = new javax.swing.JLabel();
        textLabelUltimoItem = new javax.swing.JLabel();
        botaoConfirmaItem = new javax.swing.JButton();
        painelEsquerdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spinnerUnidades = new javax.swing.JSpinner();
        labelCodigo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCodigos = new javax.swing.JList<>();
        labelNome = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaNomes = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelTotalItem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTotalCompra = new javax.swing.JLabel();
        botaoConfirmarCompra = new java.awt.Button();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        caixaLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        consultarValor = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercado");
        setBackground(new java.awt.Color(51, 51, 51));

        topPanel.setBackground(new java.awt.Color(255, 204, 204));
        topPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topPanel.setName("ultimoItem"); // NOI18N

        labelUltimoItem.setText("Último Item");

        textLabelUltimoItem.setBackground(new java.awt.Color(255, 255, 255));
        textLabelUltimoItem.setText("jLabel3");
        textLabelUltimoItem.setOpaque(true);

        botaoConfirmaItem.setText("Confirma item");
        botaoConfirmaItem.setToolTipText("confirma o item e adiciona na lista de Itens que o cliente esta comprando");
        botaoConfirmaItem.setMargin(new java.awt.Insets(2, 14, 2, 10));
        botaoConfirmaItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoConfirmaItemMouseReleased(evt);
            }
        });
        botaoConfirmaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmaItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUltimoItem)
                    .addComponent(textLabelUltimoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoConfirmaItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(labelUltimoItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textLabelUltimoItem, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addComponent(botaoConfirmaItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelEsquerdo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelEsquerdo.setLayout(new java.awt.GridLayout(8, 2));

        jLabel1.setLabelFor(labelCodigo);
        jLabel1.setText("Unidades");
        painelEsquerdo.add(jLabel1);

        spinnerUnidades.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spinnerUnidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                spinnerUnidadesMouseReleased(evt);
            }
        });
        painelEsquerdo.add(spinnerUnidades);

        labelCodigo.setBackground(new java.awt.Color(255, 255, 255));
        labelCodigo.setText("Codigo");
        labelCodigo.setOpaque(true);
        painelEsquerdo.add(labelCodigo);

        listaCodigos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCodigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaCodigosMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(listaCodigos);

        painelEsquerdo.add(jScrollPane2);

        labelNome.setBackground(new java.awt.Color(255, 255, 255));
        labelNome.setText("Nome");
        painelEsquerdo.add(labelNome);

        listaNomes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaNomesMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(listaNomes);

        painelEsquerdo.add(jScrollPane3);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setLabelFor(labelNome);
        jLabel10.setText("Valor unitario");
        jLabel10.setOpaque(true);
        painelEsquerdo.add(jLabel10);

        jLabel7.setText("jLabel7");
        painelEsquerdo.add(jLabel7);

        jLabel8.setLabelFor(labelTotalItem);
        jLabel8.setText("Total do Item");
        painelEsquerdo.add(jLabel8);

        labelTotalItem.setBackground(new java.awt.Color(255, 255, 255));
        labelTotalItem.setOpaque(true);
        painelEsquerdo.add(labelTotalItem);

        jLabel2.setText("TOTAL COMPRA");
        painelEsquerdo.add(jLabel2);

        labelTotalCompra.setBackground(new java.awt.Color(255, 255, 255));
        labelTotalCompra.setOpaque(true);
        painelEsquerdo.add(labelTotalCompra);

        botaoConfirmarCompra.setBackground(new java.awt.Color(255, 0, 51));
        botaoConfirmarCompra.setLabel("CONFIRMAR COMPRA");
        botaoConfirmarCompra.setName(""); // NOI18N
        botaoConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCompraActionPerformed(evt);
            }
        });
        painelEsquerdo.add(botaoConfirmarCompra);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 800));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setFocusCycleRoot(true);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));
        jPanel6.setLayout(new java.awt.GridLayout(1, 6, 2, 5));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Operador");
        jLabel4.setAlignmentX(1.0F);
        jPanel6.add(jLabel4);

        caixaLabel.setText("Caixa");
        jPanel6.add(caixaLabel);

        dataLabel.setText("Data");
        jPanel6.add(dataLabel);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        consultarValor.setText("Edit");
        consultarValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarValorMouseClicked(evt);
            }
        });
        jMenuBar1.add(consultarValor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        topPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaCodigosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCodigosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_listaCodigosMouseReleased

    private void listaNomesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_listaNomesMouseReleased

    private void spinnerUnidadesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinnerUnidadesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerUnidadesMouseReleased

    private void botaoConfirmaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirmaItemActionPerformed

    private void botaoConfirmaItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmaItemMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirmaItemMouseReleased

    private void consultarValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarValorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarValorMouseClicked

    private void botaoConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirmarCompraActionPerformed

    /**
     * @param args the command line arguments
   */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmaItem;
    private java.awt.Button botaoConfirmarCompra;
    private javax.swing.JLabel caixaLabel;
    private javax.swing.JMenu consultarValor;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTotalCompra;
    private javax.swing.JLabel labelTotalItem;
    private javax.swing.JLabel labelUltimoItem;
    private javax.swing.JList<String> listaCodigos;
    private javax.swing.JList<String> listaNomes;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JSpinner spinnerUnidades;
    private javax.swing.JLabel textLabelUltimoItem;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
